service: 'my-baremetal-project'
plugins:
  - serverless-esbuild
  - serverless-offline
package:
   individually: true
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
# functions
functions:

  trucks:
    handler: src/functions/trucks/index.handler
    events:
      - http:
          method: ANY
          path: trucks/
      - http:
          method: ANY
          path: "trucks/{proxy+}"
