name: Deploy to AWS

on:
  push:
    branches: [master]

jobs:
  
  deploy:
    name: Deploy AWS infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: (cd ./lambdas && npm install)

      - name: Bundle lambdas
        run: (cd ./lambdas && npx sls package)

      - name: Initialize terraform
        run: terraform init

      - name: Apply changes to infrastructure
        env:
          TF_VAR_DB_NAME: ${{ vars.DB_NAME }}
          TF_VAR_DB_USER: ${{ vars.DB_USER }}
          TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD  }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
